#docker-compose는 1버전 부터 3버전까지 있습니다. 최신 소프트웨어를 사용하기 위하여 버전을 3으로 명시
version: '3'
services:
  api:
    # Dockerfile이 있는 위치
    build: ./API
    #컨테이너 이름을 명시 가능
    #container_name: comapi-con
    #이미지 이름 명시 가능
    #image: comapi-img
    #호스트와 포트 연결 설정
    ports:
      - "5511:5511"
  plus:
    build: ./PlusAPI
    ports:
      - "6611:6611"
  ui:
    build: ./UI
    ports:
      - "8081:8081"