DROP TABLE IF EXISTS admin_sentence;

CREATE TABLE admin_sentence(
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    korean VARCHAR(255) NOT NULL,
    English VARCHAR(255) NOT NULL,
    grammar VARCHAR(255) NOT NULL,
    situation VARCHAR(255) NOT NULL,
    created_date TIMESTAMP NOT NULL,
    updated_date TIMESTAMP NOT NULL
);

DROP TABLE IF EXISTS users;

CREATE TABLE users(
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    authority VARCHAR(255) NOT NULL
);