spring:
  config:
    activate:
      on-profile: sqs-local
  kafka:
    producer:
      bootstrap-servers: 127.0.0.7:9093
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
---

spring:
  config:
    activate:
      on-profile: sqs-server
  kafka:
    producer:
      bootstrap-servers: 10.0.2.7:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

---

spring:
  config:
    activate:
      on-profile: sqs-aws
#aws profile은 kafka가 아닌 sqs를 사용
cloud:
  aws:
    region:
      static: ap-northeast-2
      auto: false
    credentials:
      access-key: AKIA3W5LLZVXZA7NAPGM
      secret-key: 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
    end-point:
      url: https://sqs.ap-northeast-2.amazonaws.com/805128883567/sqs