spring:
  config:
    activate:
      on-profile: default-default
  jpa:
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    show-sql: true
    config:
      import: kafka.yml
  logging:
    level:
      org:
        hibernate:
          sql: debug
