spring:
  config:
    activate:
      on-profile: db-local
  datasource:
    url: "jdbc:mysql://127.0.0.3:3306/english"
    username: "hwang"
    password: "5510"
  redis:
    host: 127.0.0.3
    port: 6379
server:
  port: 5510
logging:
  config: classpath:logback-local.xml

---

spring:
  config:
    activate:
      on-profile: db-server
  datasource:
    url: "jdbc:mysql://10.0.2.3:3306/english"
    username: "hwang"
    password: "5510"
server:
  port: 5511
logging:
  config: classpath:logback-server.xml
