spring:
  config:
    activate:
      on-profile: port-local
server:
  port: 6610
---

spring:
  config:
    activate:
      on-profile: port-server
server:
  port: 6611

---

spring:
  config:
    activate:
      on-profile: port-aws
server:
  port: 6612

---

spring:
  config:
    activate:
      on-profile: port-new
server:
  port: 7070