spring:
  config:
    activate:
      on-profile: default-default
  mail:
    host: smtp.gmail.com
    port: 587
    username: geungan9@gmail.com
    password: jnzsiyjxpgomcaaz
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
          timeout: 5000
  jpa:
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    show-sql: true
logging:
  level:
    org:
      hibernate:
        sql: debug
