spring:
  profiles:
    active:
      - local
    group:
      local:
        - default-default
        - port-local
        - db-local
        - sqs-aws
      server:
        - default-default
        - port-server
        - db-server
        - sqs-server
      aws:
        - default-default
        - port-aws
        - db-aws
        - sqs-aws
      test:
        - db-test
        - sqs-aws
    include:
      - default
      - port
      - db
      - sqs