spring:
  config:
    activate:
      on-profile: local
  kafka:
    consumer:
      bootstrap-servers: 127.0.0.7:9093
      group-id: foo
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false
---
spring:
  config:
    activate:
      on-profile: server
  kafka:
    consumer:
      bootstrap-servers: 10.0.2.7:9092
      group-id: foo
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false
